/**
 * Core Types Index
 *
 * Re-exports all types from the modular pipeline system
 */

// Widget configuration types
export type {
  Widget,
  WidgetMetadata,
  WidgetCategory,
  CanvasConfig,
  BleedConfig,
  SafeZoneConfig,
  PrintSize,
  FieldDefinition,
  FieldType,
  SelectOption,
  FieldValidation,
  FieldStyle,
  FontSizeRange,
  FontWeight,
  ImageDimensions,
  GeneratorType,
  FieldConditional,
  TemplateRegistry as WidgetTemplateRegistry,
  Template,
  LayoutConfig,
  GridConfig,
  FlexConfig,
  TemplateFieldConfig,
  Position,
  Size,
  TemplateFieldStyle,
  AnimationType,
  BackgroundConfig,
  BackgroundDefault,
  GradientConfig,
  GradientStop,
  PatternConfig,
  ColorScheme,
  Decoration,
  DecorationStyle,
  PromptConfig,
  BackendPrompts,
  SystemPrompt,
  PromptTemplates,
  BackgroundGenerationPrompt,
  StyleTransferPrompt,
  CompositingPrompt,
  NanaBananaPrompt,
  LayerConfig,
  BlendMode,
  GenericCompositingPrompt,
  FrontendPrompts,
  UIPrompts,
  WorkflowPrompt,
  WorkflowStep,
  SuggestionPrompts,
  StyleSuggestion,
  ValidationPrompts,
  HelpPrompts,
  HelpSection,
  AssetConfig,
  ExportConfig,
  ExportFormat,
  ResolutionConfig,
  AIWorkflowConfig,
  AIProvider,
  AIFeatures,
} from './widget.types';

// AI service types
export type {
  AIServiceProvider,
  AICapabilities,
  AIGenerationRequest,
  ReferenceImage,
  SafeZone,
  AICompositionRequest,
  CompositionLayer,
  AIStyleTransferRequest,
  AIGenerationResponse,
  GeneratedImage,
  GenerationMetadata,
  AIError,
  UsageInfo,
  CostEstimate,
  CostBreakdown,
  PromptBuilder,
  PromptTemplate,
  PromptSection,
  PromptVariables,
  AIWorkflowState,
  AIWorkflowStatus,
  NanaBananaConfig,
  MidjourneyConfig,
  OpenAIConfig,
  StableDiffusionConfig,
  ReplicateConfig,
  AIProviderConfig,
} from './ai.types';

// Preset types
export type {
  Preset,
  PresetDesign,
  PresetAISettings,
  PresetReferenceImage,
  PresetExportSettings,
  PresetCollection,
  PresetStorage,
  PresetSearchQuery,
  ExportedPresets,
  ExportedAsset,
  QuickPreset,
  QuickPresetType,
  QuickPresetData,
  FontCombo,
  LayoutStyle,
  AIStyle,
  PresetEventType,
  PresetEvent,
  PresetEventHandler,
} from './preset.types';

// Pipeline types
export type {
  PipelineEngine,
  PipelineStateCallback,
  PipelineState,
  PipelineStatus,
  DesignState,
  RenderState,
  ValidationError,
  HistoryState,
  PipelineSnapshot,
  AIGenerationOptions,
  RenderEngine,
  RenderInput,
  RenderedOutput,
  ExportRenderOptions,
  GuideOptions,
  ExportEngine,
  ExportInput,
  ExportOptions,
  ExportMetadata,
  ExportResult,
  WidgetRegistry,
  TemplateRegistry,
  PipelineEventType,
  PipelineEvent,
  PipelineEventHandler,
  PipelineConfig,
} from './pipeline.types';
